### ISSUE TITLE
Regarding the display of multiple document pages

### ISSUE THREAD

**Issue by wolono** [nisabmohd/Aria-Docs#14]
Can you consider adding a document collection page?
## Effect
![image](https://github.com/user-attachments/assets/057e7d3a-b261-4e85-a647-30a957cbdd96)

**Comment by nisabmohd** [comment]
Need an proper explanation what is expected

**Comment by wolono** [comment]
Similar to a blog list page, add a page to the document to display the documents in the docs directory. Of course, this page is only meaningful when there are multiple documents
When opened https://ariadocs.vercel.app/docs/ When linking
![image](https://github.com/user-attachments/assets/f927066a-21a7-4553-94d2-5c263daf3e39)
When there are multiple documents in the contents/docs directory, its structure is like this
```
contents/
├── docs/
│   ├── Document 1/
│   │   ├── index.mdx
│   │   ├── install.mdx
│   │   ├── start using 
│   │        ├── index.mdx
│   │        ├── home.mdx
│   ├── Document 2/
│   │   ├── index.mdx
│   │   ├── install.mdx
│   │   ├── start using 
│   │        ├── index.mdx
│   │        ├── home.mdx
│   ├── Document 3/
│   │   ├── index.mdx
│   │   ├── install.mdx
│   │   ├── start using 
│   │        ├── index.mdx
│   │        ├── home.mdx
│   ├── Document 4/
│   │   ├── index.mdx
│   │   ├── install.mdx
│   │   ├── start using 
│   │        ├── index.mdx
│   │        ├── home.mdx
```
The document list page will automatically generate a link based on the folder name. If you want to implement a cover image, you can use a custom image or icon, or you don't need an image by default. This is probably the idea. I'm not sure if my expression is clear

**Comment by wolono** [comment]
Is there a channel for communication, such as Discord

**Comment by nisabmohd** [comment]
![image](https://github.com/user-attachments/assets/15ce7f81-05de-4f15-a5c7-cd6e77e5500b)


Done closing this issue
