### ISSUE TITLE
404 page is misaligned

### ISSUE THREAD

**Issue by wolono** [nisabmohd/Aria-Docs#15]
![image](https://github.com/user-attachments/assets/7e3ff18a-c5a0-44ef-8c78-0b16eb2a976e)
Recommended Repair

**Comment by nisabmohd** [comment]
It is built that way. just generalized the page can be changed according to needs

**Comment by nisabmohd** [comment]
You can check i have made some change to error and not found page

**Comment by wolono** [comment]
Great, you're always very timely
