### ISSUE TITLE
Used @ Amazon

### ISSUE THREAD

**Issue by itsfaraaz** [nisabmohd/Aria-Docs#18]
FYI, we're using your template internally at Amazon for our own documentation to internal teams. Great work on this template, and thanks for all your hard work!

**Comment by nisabmohd** [comment]
Thank you! I'm glad to hear AriaDocs is being used by your team. Let me know if there’s anything I can help with!

**Comment by nisabmohd** [comment]
Thank you! I'm glad to hear AriaDocs is being used by your team. Let me
know if there’s anything I can help with!

By the way, if there are any roles at Amazon that might be a good fit, I'd
appreciate it if you could refer me or keep me in mind. Thanks again!
