### ISSUE TITLE
Please add versions too like in docs so for docs/v1/ docs/v2/ and a special documentation version changing dropdown so that users can switch between versions too

### ISSUE THREAD

**Issue by amyssnippet** [nisabmohd/Aria-Docs#8]
Please do it asap as Im eagerly waiting for your update

**Comment by erfjab** [comment]
Good idea 🤌

**Comment by nisabmohd** [comment]
I'm making this template very generic, but if you need this dropdown feature, I can share a code snippet for it soon.

**Comment by erfjab** [comment]
> I'm making this template very generic, but if you need this dropdown feature, I can share a code snippet for it soon.

Awesome 👀

**Comment by amyssnippet** [comment]
Bro I'm eagerly waiting

**Comment by nisabmohd** [comment]
Bro already I'm on it please wait its a huge change.

![image](https://github.com/user-attachments/assets/cc5f4aec-98de-45e0-8153-46c3a9947ffa)

I will push the changes into branch and will notify you. please be patient

**Comment by nisabmohd** [comment]
Hey guys it done please checkout the branch `version_docs` 
https://github.com/nisabmohd/Aria-Docs/tree/version_docs 
![image](https://github.com/user-attachments/assets/ea7cb873-316d-4f76-85fd-ce2c04dd19fe)


I have added a dropdown for version select , pagination links ,search ,SSG and all I covered
please let me know if any bugs or enhancement

**Comment by nisabmohd** [comment]
Guys do check out minimal version branch too.. simple and ready to get started with simple setup

**Comment by uptonking** [comment]
> Hey guys its done!!!! please checkout the branch `version_docs` [`version_docs`](https://github.com/nisabmohd/Aria-Docs/tree/version_docs?rgh-link-date=2024-09-08T12%3A14%3A30.000Z) ![image](https://github.com/user-attachments/assets/ea7cb873-316d-4f76-85fd-ce2c04dd19fe)
> 
> I have added a dropdown for version select , pagination links ,search ,SSG and all I covered please let me know if any bugs or enhancement


🤔 why does the current offcial website have much fewer features than your screenshot

**Comment by nisabmohd** [comment]
I've changed this from template to library and all features are supported
you can check the documentation. The templates are deprecated now but still
exist in other branch which you mentioned
